### ISSUE TITLE
Add support for custom item selectors

### ISSUE THREAD

**Issue by weberval** [adfinis/timedctl#38]
Add support for other item selectors than fzf, e.g. bemenu or dmenu.

This could either be done by using exec in code or by providing options for retrieving cost centres for custom scripting.

(`timedctl --customer (timedctl --retrieve_customers | bemenu) ... "Description"`

**Comment by gianklug** [comment]
Hey! Thanks for the idea, I'll implement a `timedctl get (customers|projects|tasks)` for that.

**Comment by gianklug** [comment]
@weberval implemented in 948dcc6f072f3cb7d3bb302316e945c66eca336f, however quite messy now, will have to refactor this.
