### ISSUE TITLE
Set custom time when starting an activity

### ISSUE THREAD

**Issue by pree** [adfinis/timedctl#49]
It would be good to be able to set a custom time when starting an activity, for example when I'm late with the start command.

This could look something like: `timedctl activity start "comment" --start "10:00"` 

I don't know if this can be done in timed when starting an activity, alternatively, you can implement a command to edit the current running activity, like how it's done in timed itself.
Also, you can probably add flags for non-billable / needs-review when editing the current activity (https://github.com/adfinis/timedctl/issues/16)

**Comment by gianklug** [comment]
Implemented in https://github.com/adfinis/timedctl/commit/004b0c0fe765aef39d6af02cf910edb18562e724
